FROM python:3.10-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV PORT=8503
CMD ["sh","-c","streamlit run app/streamlit_app.py --server.port ${PORT} --server.address 0.0.0.0"]
